const express = require('express')
const editAvt = require('../api/account/editAvt')
const editInfo = require('../api/account/editInfo')
const create = require('../api/account/create')
const getOne = require('../api/account/getOne')
const auth = require('../middlewares/auth')
const remove = require('../api/account/delete')
const getAll = require('../api/account/getAll')
const router = express.Router()

router.delete('/:_id', auth, remove)
router.put('/:_id/avt', auth, editAvt)
router.put('/:_id', auth, editInfo)
router.post('/', auth, create)
router.get('/:_id', auth, getOne)
router.get('/', auth, getAll)
module.exports = router